name: drt
version: 1.0.0
description: Print a Dart release tag name.
repository: https://github.com/chrisnorman7/drt

environment:
  sdk: ^3.10.2

dependencies:
  pubspec_parse: ^1.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
